Repository 100-hours-a-week/10-team-10bob-siungongsi-be, pull requests merged in 2025-03, with the labels that each got.

#61 feat: 회원가입 및 로그인 API 개발
  src/main/java/org/bob/siungongsi/controller/AuthController.java
  src/main/java/org/bob/siungongsi/domain/UserEntity.java
  src/main/java/org/bob/siungongsi/dto/ApiResponseCode.java
  src/main/java/org/bob/siungongsi/repository/AuthRepository.java
  src/main/java/org/bob/siungongsi/service/AuthService.java
Labels: 기능 개발

#60 feat: 기업 검색 API 개발
  src/main/java/org/bob/siungongsi/controller/CompanyController.java
  src/main/java/org/bob/siungongsi/domain/CompanyNameAutofillEntity.java
  src/main/java/org/bob/siungongsi/repository/CompanyNameAutofillRepository.java
  src/main/java/org/bob/siungongsi/service/CompanyService.java
Labels: 기능 개발

#64 공시 데이터 처리 스케쥴러 개발
  .github/workflows/dev-deploy.yml
  .gitignore
  build.gradle
  src/main/java/org/bob/siungongsi/SiungongsiApplication.java
  src/main/java/org/bob/siungongsi/client/LoggingInterceptor.java
  src/main/java/org/bob/siungongsi/client/OpenDartReader.java
  src/main/java/org/bob/siungongsi/client/RestClientConfig.java
  src/main/java/org/bob/siungongsi/client/RetryClientHttpRequestInterceptor.java
  src/main/java/org/bob/siungongsi/client/clientinterface/GoogleAiClientInterface.java
  src/main/java/org/bob/siungongsi/client/clientinterface/OpenDartClientInterface.java
  src/main/java/org/bob/siungongsi/client/dto/GoogleAiDtos.java
  src/main/java/org/bob/siungongsi/client/dto/OpenDartDtos.java
  src/main/java/org/bob/siungongsi/config/AwsCredentialsProperties.java
  src/main/java/org/bob/siungongsi/config/EnablePropertiesConfig.java
  src/main/java/org/bob/siungongsi/config/JpaAuditConfig.java
  src/main/java/org/bob/siungongsi/config/MessageQueueConfig.java
  src/main/java/org/bob/siungongsi/config/S3Properties.java
  src/main/java/org/bob/siungongsi/config/SchedulerConfig.java
  src/main/java/org/bob/siungongsi/config/SqsProperties.java
  src/main/java/org/bob/siungongsi/domain/BaseTimeEntity.java
  src/main/java/org/bob/siungongsi/domain/CompanyEntity.java
  src/main/java/org/bob/siungongsi/domain/GongsiEntity.java
  src/main/java/org/bob/siungongsi/domain/ModifiableEntity.java
  src/main/java/org/bob/siungongsi/domain/ProcessingFailedGongsiEntity.java
  src/main/java/org/bob/siungongsi/domain/TodayProcessedGongsiEntity.java
  src/main/java/org/bob/siungongsi/domain/UserEntity.java
  src/main/java/org/bob/siungongsi/event/GongsiMessage.java
  src/main/java/org/bob/siungongsi/exception/CustomException.java
  src/main/java/org/bob/siungongsi/exception/GlobalExceptionHandler.java
  src/main/java/org/bob/siungongsi/repository/CompanyRepository.java
  src/main/java/org/bob/siungongsi/repository/GongsiRepository.java
  src/main/java/org/bob/siungongsi/repository/ProcessingFailedGongsiRepository.java
  src/main/java/org/bob/siungongsi/repository/TodayProcessedGongsiRepository.java
  src/main/java/org/bob/siungongsi/scheduler/GongsiProcessingScheduler.java
  src/main/java/org/bob/siungongsi/service/FileService.java
  src/main/java/org/bob/siungongsi/service/GongsiSummarizer.java
  src/main/java/org/bob/siungongsi/service/MessageListener.java
  src/main/java/org/bob/siungongsi/service/MessageSender.java
  src/main/java/org/bob/siungongsi/service/RankedCompanyManager.java
  src/main/java/org/bob/siungongsi/service/TodayProcessedGongsiManager.java
  src/main/java/org/bob/siungongsi/service/ZipFileReader.java
  src/main/java/org/bob/siungongsi/util/GongsiDataProcessingTimeChecker.java
  src/main/java/org/bob/siungongsi/util/TextUtil.java
  src/main/resources/application.yml
Labels: 기능 개발

#66 feat: 약관 불러오기 API 개발
  src/main/java/org/bob/siungongsi/controller/AuthController.java
  src/main/java/org/bob/siungongsi/controller/dto/TermsResponse.java
  src/main/java/org/bob/siungongsi/domain/TermEntity.java
  src/main/java/org/bob/siungongsi/repository/TermRepository.java
  src/main/java/org/bob/siungongsi/repository/UserRepository.java
  src/main/java/org/bob/siungongsi/service/AuthService.java
Labels: 기능 개발

#69 local, dev 환경분리
  Dockerfile
  src/main/java/org/bob/siungongsi/client/RestClientConfig.java
  src/main/java/org/bob/siungongsi/scheduler/GongsiProcessingScheduler.java
  src/main/java/org/bob/siungongsi/service/MessageListener.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 기능 개발

#72 feat: sqs 메시지 송, 수신 비동기 처리
  src/main/java/org/bob/siungongsi/scheduler/GongsiProcessingScheduler.java
  src/main/java/org/bob/siungongsi/service/MessageListener.java
Labels: 버그-일반

#74 feat: 공시목록조회 API 개발
  src/main/java/org/bob/siungongsi/controller/GongsiController.java
  src/main/java/org/bob/siungongsi/controller/dto/CompanyResponse.java
  src/main/java/org/bob/siungongsi/controller/dto/GongsiResponse.java
  src/main/java/org/bob/siungongsi/controller/dto/PaginationResponse.java
  src/main/java/org/bob/siungongsi/repository/GongsiRepository.java
  src/main/java/org/bob/siungongsi/service/GongsiService.java
Labels: 기능 개발

#75 feat: 인증 필터 추가로 헤더에서 유저 id 받아오기
  build.gradle
  src/main/java/org/bob/siungongsi/config/SecurityConfig.java
  src/main/java/org/bob/siungongsi/controller/AuthController.java
  src/main/java/org/bob/siungongsi/controller/dto/AuthRequest.java
  src/main/java/org/bob/siungongsi/controller/spec/AuthControllerSpec.java
  src/main/java/org/bob/siungongsi/domain/UserEntity.java
  src/main/java/org/bob/siungongsi/security/KakaoAuthFilter.java
  src/main/java/org/bob/siungongsi/security/KakaoAuthenticationToken.java
  src/main/java/org/bob/siungongsi/service/AuthService.java
  src/main/java/org/bob/siungongsi/service/KakaoAuthService.java
  src/main/java/org/bob/siungongsi/service/UserService.java
Labels: 기능 개발

#76 개발환경 Cors 관련 속성 작성
  src/main/java/org/bob/siungongsi/config/CorsConfig.java
  src/main/java/org/bob/siungongsi/config/SecurityConfig.java
Labels: 기능 개발

#77 feat: 알림허용상태변경 API, 알림허용여부API 개발
  src/main/java/org/bob/siungongsi/controller/UserController.java
  src/main/java/org/bob/siungongsi/controller/dto/UserRequest.java
  src/main/java/org/bob/siungongsi/controller/dto/UserResponse.java
  src/main/java/org/bob/siungongsi/service/UserService.java
Labels: 기능 개발

#78 feat: 알림 관련 API 개발
  src/main/java/org/bob/siungongsi/controller/NotificationController.java
  src/main/java/org/bob/siungongsi/controller/dto/NotificationRequest.java
  src/main/java/org/bob/siungongsi/controller/dto/NotificationResponse.java
  src/main/java/org/bob/siungongsi/controller/spec/NotificationControllerSpec.java
  src/main/java/org/bob/siungongsi/domain/NotiHistoryEntity.java
  src/main/java/org/bob/siungongsi/repository/CompanyRepository.java
  src/main/java/org/bob/siungongsi/repository/NotificationRepository.java
  src/main/java/org/bob/siungongsi/service/NotificationService.java
Labels: 기능 개발

#80 feat: 로그인 API에 회원여부 추가
  src/main/java/org/bob/siungongsi/controller/AuthController.java
  src/main/java/org/bob/siungongsi/controller/dto/AuthResponse.java
  src/main/java/org/bob/siungongsi/service/AuthService.java
  src/main/java/org/bob/siungongsi/service/KakaoAuthService.java
Labels: 기능 개발

#83 feat: 공시상세조회 API 개발
  src/main/java/org/bob/siungongsi/client/clientinterface/KoreanInvestmentClient.java
  src/main/java/org/bob/siungongsi/controller/GongsiController.java
  src/main/java/org/bob/siungongsi/controller/spec/GongsiControllerSpec.java
  src/main/java/org/bob/siungongsi/domain/GongsiViewHistoryEntity.java
  src/main/java/org/bob/siungongsi/dto/ApiResponseCode.java
  src/main/java/org/bob/siungongsi/repository/GongsiViewHistoryRepository.java
  src/main/java/org/bob/siungongsi/service/GongsiService.java
  src/main/java/org/bob/siungongsi/service/KoreanInvestmentTokenManager.java
  src/main/resources/application-local.yml
Labels: 기능 개발

#86 feat: 조회수로 정렬하기 기능 개발
  src/main/java/org/bob/siungongsi/controller/dto/GongsiResponse.java
  src/main/java/org/bob/siungongsi/repository/GongsiRepository.java
  src/main/java/org/bob/siungongsi/service/GongsiService.java
Labels: 기능 개발

#88 feat: 기업 검색 API 에러 처리 추가
  src/main/java/org/bob/siungongsi/controller/CompanyController.java
  src/main/java/org/bob/siungongsi/repository/CompanyNameAutofillRepository.java
Labels: 기능 개발

#87 feat: 알림 관련 에러 처리 추가
  src/main/java/org/bob/siungongsi/controller/NotificationController.java
  src/main/java/org/bob/siungongsi/repository/CompanyRepository.java
  src/main/java/org/bob/siungongsi/repository/UserRepository.java
  src/main/java/org/bob/siungongsi/service/NotificationService.java
Labels: 기능 개발

#93 feat: 기업 검색 결과 - 5개로 제한
  src/main/java/org/bob/siungongsi/repository/CompanyNameAutofillRepository.java
  src/main/java/org/bob/siungongsi/service/CompanyService.java
Labels: 기능 개발

#98 feat: 회원가입에 약관 동의 추가 및 리팩토링
  src/main/java/org/bob/siungongsi/controller/AuthController.java
  src/main/java/org/bob/siungongsi/controller/dto/AuthRequest.java
  src/main/java/org/bob/siungongsi/domain/UserAgreedTermEntity.java
  src/main/java/org/bob/siungongsi/dto/ApiResponseCode.java
  src/main/java/org/bob/siungongsi/repository/TermRepository.java
  src/main/java/org/bob/siungongsi/repository/UserAgreedTermRepository.java
  src/main/java/org/bob/siungongsi/repository/UserRepository.java
  src/main/java/org/bob/siungongsi/service/AuthService.java
  src/main/java/org/bob/siungongsi/service/KakaoAuthService.java
  src/main/java/org/bob/siungongsi/service/UserService.java
Labels: 기능 개발

#105 fix: 알림제거 데이터 삭제 안되는 문제
  src/main/java/org/bob/siungongsi/repository/NotificationRepository.java
  src/main/java/org/bob/siungongsi/service/NotificationService.java
Labels: 버그-심각

#106 feat: 로그인 토큰 바디에서 헤더로 수정
  src/main/java/org/bob/siungongsi/controller/AuthController.java
  src/main/java/org/bob/siungongsi/controller/dto/AuthRequest.java
  src/main/java/org/bob/siungongsi/controller/spec/AuthControllerSpec.java
  src/main/java/org/bob/siungongsi/service/AuthService.java
Labels: 버그-심각, 리팩토링

#107 feat: 회원가입 토큰 바디에서 헤더로 받게 수정
  src/main/java/org/bob/siungongsi/controller/AuthController.java
  src/main/java/org/bob/siungongsi/controller/dto/AuthRequest.java
  src/main/java/org/bob/siungongsi/controller/spec/AuthControllerSpec.java
  src/main/java/org/bob/siungongsi/service/AuthService.java
Labels: 리팩토링

#101 테스트 코드 세팅
  .github/workflows/test.yml
  build.gradle
  src/main/java/org/bob/siungongsi/domain/TodayProcessedGongsiEntity.java
  src/test/java/org/bob/siungongsi/controller/AdminControllerTest.java
  src/test/java/org/bob/siungongsi/repository/TodayProcessedGongsiRepositoryTest.java
  src/test/java/org/bob/siungongsi/service/TodayProcessedGongsiManagerTest.java
  src/test/java/org/bob/siungongsi/service/TodayProcessedGongsiServiceTest.java
  src/test/resources/application-test.yml
Labels: 기능 개발

#118 기업명 자동완성 데이터 생성 API 개발
  src/main/java/org/bob/siungongsi/controller/AdminController.java
  src/main/java/org/bob/siungongsi/controller/spec/AdminControllerSpec.java
  src/main/java/org/bob/siungongsi/domain/CompanyEntity.java
  src/main/java/org/bob/siungongsi/domain/CompanyNameAutofillEntity.java
  src/main/java/org/bob/siungongsi/repository/CompanyRepository.java
  src/main/java/org/bob/siungongsi/service/CompanyNameAutofillGenerator.java
  src/test/java/org/bob/siungongsi/controller/AdminControllerTest.java
  src/test/java/org/bob/siungongsi/repository/CompanyRepositoryTest.java
  src/test/java/org/bob/siungongsi/service/CompanyNameAutofillGeneratorTest.java
Labels: 기능 개발

#121 feat: JWT 추가
  .github/workflows/dev-deploy.yml
  build.gradle
  src/main/java/org/bob/siungongsi/config/SecurityConfig.java
  src/main/java/org/bob/siungongsi/controller/AdminController.java
  src/main/java/org/bob/siungongsi/controller/AuthController.java
  src/main/java/org/bob/siungongsi/controller/GongsiController.java
  src/main/java/org/bob/siungongsi/controller/UserController.java
  src/main/java/org/bob/siungongsi/controller/dto/AuthResponse.java
  src/main/java/org/bob/siungongsi/controller/spec/AdminControllerSpec.java
  src/main/java/org/bob/siungongsi/domain/UserAgreedTermsEntity.java
  src/main/java/org/bob/siungongsi/repository/UserRepository.java
  src/main/java/org/bob/siungongsi/security/JwtAuthFilter.java
  src/main/java/org/bob/siungongsi/security/JwtAuthenticationToken.java
  src/main/java/org/bob/siungongsi/security/JwtProvider.java
  src/main/java/org/bob/siungongsi/security/KakaoAuthFilter.java
  src/main/java/org/bob/siungongsi/security/KakaoAuthenticationToken.java
  src/main/java/org/bob/siungongsi/service/AuthService.java
  src/main/java/org/bob/siungongsi/service/KakaoAuthService.java
  src/main/java/org/bob/siungongsi/service/NotificationService.java
  src/main/java/org/bob/siungongsi/service/UserService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/test/java/org/bob/siungongsi/controller/AdminControllerTest.java
Labels: 리팩토링

#122 실제 약관 데이터를 반환하도록 변경
  src/main/java/org/bob/siungongsi/controller/AuthController.java
Labels: 기능 개발

#129 API KEY 관리 기능 개발
  src/main/java/org/bob/siungongsi/client/clientinterface/KoreanInvestmentClient.java
  src/main/java/org/bob/siungongsi/domain/ApiKeyStoreEntity.java
  src/main/java/org/bob/siungongsi/dto/ApiResponseCode.java
  src/main/java/org/bob/siungongsi/repository/ApiKeyStoreRepository.java
  src/main/java/org/bob/siungongsi/scheduler/ApiKeyRefreshScheduler.java
  src/main/java/org/bob/siungongsi/service/ApiKeyStoreManager.java
  src/main/java/org/bob/siungongsi/service/KoreanInvestmentTokenManager.java
Labels: 기능 개발

#130 feat: 에러 처리 필터 추가
  src/main/java/org/bob/siungongsi/config/SecurityConfig.java
  src/main/java/org/bob/siungongsi/controller/AuthController.java
  src/main/java/org/bob/siungongsi/security/ExceptionHandlerFilter.java
  src/main/java/org/bob/siungongsi/security/JwtAuthFilter.java
  src/main/java/org/bob/siungongsi/service/AuthService.java
  src/main/java/org/bob/siungongsi/service/NotificationService.java
Labels: 기능 개발

#133 cors 관련 속성 추가
  src/main/java/org/bob/siungongsi/config/CorsConfig.java
  src/main/java/org/bob/siungongsi/config/CorsProperties.java
  src/main/java/org/bob/siungongsi/config/EnablePropertiesConfig.java
  src/main/java/org/bob/siungongsi/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 버그-일반

#134 공시 알림 스케쥴러 개발
  .github/workflows/dev-deploy.yml
  build.gradle
  src/main/java/org/bob/siungongsi/domain/GongsiSentStatusEntity.java
  src/main/java/org/bob/siungongsi/domain/NotiHistoryEntity.java
  src/main/java/org/bob/siungongsi/domain/PushStatus.java
  src/main/java/org/bob/siungongsi/domain/UserEntity.java
  src/main/java/org/bob/siungongsi/dto/ApiResponseCode.java
  src/main/java/org/bob/siungongsi/repository/GongsiSentStatusRepository.java
  src/main/java/org/bob/siungongsi/repository/NotificationRepository.java
  src/main/java/org/bob/siungongsi/scheduler/PushNotiWorker.java
  src/main/java/org/bob/siungongsi/service/FcmService.java
  src/main/java/org/bob/siungongsi/service/MessageListener.java
  src/main/java/org/bob/siungongsi/service/PushNotiService.java
  src/main/java/org/bob/siungongsi/service/UserService.java
  src/main/resources/application-dev.yml
Labels: 기능 개발

#140 Short 를 boolean 으로 바꾸며 누락되었던 부분을 수정
  src/main/java/org/bob/siungongsi/repository/UserRepository.java
  src/main/java/org/bob/siungongsi/service/NotificationService.java
Labels: 버그-심각

#145 새로운 API KEY 가져올 때 인메모리에 반영되도록 수정
  src/main/java/org/bob/siungongsi/domain/ApiKeyStoreEntity.java
  src/main/java/org/bob/siungongsi/repository/ApiKeyStoreRepository.java
  src/main/java/org/bob/siungongsi/scheduler/ApiKeyRefreshScheduler.java
  src/main/java/org/bob/siungongsi/service/ApiKeyStoreManager.java
Labels: 버그-심각
