Repository 100-hours-a-week/10-team-10bob-siungongsi-be, pull requests merged in 2025-04, with the labels that each got.

#155 SecurityConfig Api, Batch 분리
  src/main/java/org/bob/siungongsi/config/SecurityConfigForApi.java
  src/main/java/org/bob/siungongsi/config/SecurityConfigForBatch.java
Labels: 기능 개발, BE

#156 batch 배포
  src/main/java/org/bob/siungongsi/config/SecurityConfigForApi.java
  src/main/java/org/bob/siungongsi/config/SecurityConfigForBatch.java
Labels: BE

#148 fix: 최대 알림 구독 기업 수 초과 에러 수정
  src/main/java/org/bob/siungongsi/dto/ApiResponseCode.java
  src/main/java/org/bob/siungongsi/repository/NotificationRepository.java
  src/main/java/org/bob/siungongsi/service/NotificationService.java
  src/main/java/org/bob/siungongsi/service/UserService.java
Labels: 버그-일반

#162 HealthCheck Endpoint 작성
  src/main/java/org/bob/siungongsi/controller/HealthCheckController.java
  src/main/java/org/bob/siungongsi/security/JwtAuthFilter.java
Labels: DEV, BE

#161 CompanyRepository Id 자료형 변경, 잘못된 매개변수명 변경, CompanyEntity 중복된 어노테이션 제거 작업
  src/main/java/org/bob/siungongsi/domain/CompanyEntity.java
  src/main/java/org/bob/siungongsi/repository/CompanyRepository.java
  src/main/java/org/bob/siungongsi/service/GongsiService.java
  src/main/java/org/bob/siungongsi/service/PushNotiService.java
Labels: BE

#170 health check endpoint 추가
  src/main/java/org/bob/siungongsi/controller/HealthCheckController.java
  src/main/java/org/bob/siungongsi/security/JwtAuthFilter.java
Labels: DEV, BE

#172 release 배포
  .github/workflows/prod-deploy.yml
  src/main/java/org/bob/siungongsi/controller/HealthCheckController.java
  src/main/java/org/bob/siungongsi/dto/ApiResponseCode.java
  src/main/java/org/bob/siungongsi/exception/CustomException.java
  src/main/java/org/bob/siungongsi/exception/GlobalExceptionHandler.java
  src/main/java/org/bob/siungongsi/security/JwtAuthFilter.java
  src/main/java/org/bob/siungongsi/security/JwtProvider.java
  src/main/java/org/bob/siungongsi/service/AuthService.java
  src/main/java/org/bob/siungongsi/service/FcmService.java
  src/main/java/org/bob/siungongsi/service/KakaoAuthService.java
  src/main/java/org/bob/siungongsi/service/NotificationService.java
  src/main/java/org/bob/siungongsi/service/UserService.java
Labels: DEV, BE

#177 feat: FCM 메시지에 Notification 추가
  src/main/java/org/bob/siungongsi/service/FcmService.java
Labels: BE

#182 fix: 구독정보 동시성 이슈 해결
  src/main/java/org/bob/siungongsi/dto/ApiResponseCode.java
  src/main/java/org/bob/siungongsi/repository/NotificationRepository.java
  src/main/java/org/bob/siungongsi/service/NotificationService.java
Labels: BE

#185 feat: circuit breaker 구현 및 알림 추가 에러 처리
  build.gradle
  src/main/java/org/bob/siungongsi/client/clientinterface/KoreanInvestmentClient.java
  src/main/java/org/bob/siungongsi/config/Resilience4jConfig.java
  src/main/java/org/bob/siungongsi/dto/ApiResponseCode.java
  src/main/java/org/bob/siungongsi/exception/GlobalExceptionHandler.java
  src/main/java/org/bob/siungongsi/repository/UserAgreedTermRepository.java
  src/main/java/org/bob/siungongsi/repository/UserRepository.java
  src/main/java/org/bob/siungongsi/service/NotificationService.java
Labels: 기능 개발, 리팩토링, BE

#190 함수 내 문자열 상수화 및 오버로드 추가
  src/main/java/org/bob/siungongsi/service/GongsiSummarizer.java
Labels: 리팩토링

#188 feat: 기업 검색 에러 처리 추가
  build.gradle
  src/main/java/org/bob/siungongsi/controller/NotificationController.java
  src/main/java/org/bob/siungongsi/controller/spec/NotificationControllerSpec.java
  src/main/java/org/bob/siungongsi/exception/GlobalExceptionHandler.java
Labels: 기능 개발, 리팩토링, BE

#192 개발 편의 API 분리 (기존 AdminController 분리)
  src/main/java/org/bob/siungongsi/api/controller/DevSupportController.java
  src/main/java/org/bob/siungongsi/api/controller/spec/DevSupportControllerSpec.java
  src/main/java/org/bob/siungongsi/batch/controller/BatchSupportController.java
  src/main/java/org/bob/siungongsi/batch/controller/spec/BatchSupportControllerSpec.java
  src/main/java/org/bob/siungongsi/common/security/JwtAuthFilter.java
  src/main/java/org/bob/siungongsi/common/security/JwtProvider.java
Labels: BE

#196 개발환경 swagger 에서 직접 지정한 URL 로 요청하도록 변경
  src/main/java/org/bob/siungongsi/common/config/ApiDocsConfig.java
  src/main/resources/application-dev.yml
Labels: 버그-일반, BE

#197 스프링 로그백 적용
  src/main/java/org/bob/siungongsi/api/client/clientinterface/KoreanInvestmentClient.java
  src/main/java/org/bob/siungongsi/api/scheduler/ApiKeyRefreshScheduler.java
  src/main/java/org/bob/siungongsi/api/service/GongsiService.java
  src/main/java/org/bob/siungongsi/common/filter/RequestIdFilter.java
  src/main/resources/application-batch.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/logback-spring.xml
Labels: BE

#201 chore: dev 환경 로깅 레벨 INFO 로 변경
  src/main/resources/application-dev.yml
Labels: BE

#203 ThridParty API 에 로깅 추가
  src/main/java/org/bob/siungongsi/api/client/clientinterface/KoreanInvestmentClient.java
  src/main/java/org/bob/siungongsi/api/service/GongsiService.java
  src/main/java/org/bob/siungongsi/batch/ThirdPartyApiLoggingAspect.java
  src/main/java/org/bob/siungongsi/batch/client/clientinterface/GoogleAiClientWrapper.java
  src/main/java/org/bob/siungongsi/batch/client/clientinterface/OpenDartClientWrapper.java
  src/main/java/org/bob/siungongsi/batch/scheduler/PushNotiWorker.java
  src/main/java/org/bob/siungongsi/batch/service/FcmService.java
  src/main/java/org/bob/siungongsi/batch/service/GongsiSummarizer.java
  src/main/java/org/bob/siungongsi/batch/service/OpenDartReader.java
  src/main/java/org/bob/siungongsi/batch/service/PushNotiService.java
Labels: BE

#204 batch scheduling 로깅 추가
  src/main/java/org/bob/siungongsi/api/scheduler/ApiKeyRefreshScheduler.java
  src/main/java/org/bob/siungongsi/api/service/ApiKeyStoreManager.java
  src/main/java/org/bob/siungongsi/batch/scheduler/GongsiProcessingScheduler.java
  src/main/java/org/bob/siungongsi/batch/scheduler/MessageListener.java
  src/main/java/org/bob/siungongsi/batch/service/OpenDartReader.java
  src/main/java/org/bob/siungongsi/batch/service/RankedCompanyManager.java
Labels: BE

#205 전역적으로 사용되는 요소에 로깅 추가
  src/main/java/org/bob/siungongsi/common/aop/ApiPerformanceLoggerAspect.java
  src/main/java/org/bob/siungongsi/common/exception/GlobalExceptionHandler.java
Labels: BE

#202 feat: 로그아웃 구현 - redis, 블랙리스트 구현
  build.gradle
  src/main/java/org/bob/siungongsi/api/config/SecurityConfigForApi.java
  src/main/java/org/bob/siungongsi/api/controller/AuthController.java
  src/main/java/org/bob/siungongsi/api/controller/spec/AuthControllerSpec.java
  src/main/java/org/bob/siungongsi/api/service/AuthBlackListService.java
  src/main/java/org/bob/siungongsi/api/service/AuthService.java
  src/main/java/org/bob/siungongsi/common/config/RedisConfig.java
  src/main/java/org/bob/siungongsi/common/dto/ApiResponseCode.java
  src/main/java/org/bob/siungongsi/common/security/JwtAuthFilter.java
  src/main/java/org/bob/siungongsi/common/security/JwtProvider.java
  src/main/java/org/bob/siungongsi/common/util/RedisUtils.java
  src/main/resources/application-batch.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: 기능 개발, BE

#209 Revert "feat: 로그아웃 구현 - redis, 블랙리스트 구현"
  build.gradle
  src/main/java/org/bob/siungongsi/api/config/SecurityConfigForApi.java
  src/main/java/org/bob/siungongsi/api/controller/AuthController.java
  src/main/java/org/bob/siungongsi/api/controller/spec/AuthControllerSpec.java
  src/main/java/org/bob/siungongsi/api/service/AuthBlackListService.java
  src/main/java/org/bob/siungongsi/api/service/AuthService.java
  src/main/java/org/bob/siungongsi/common/config/RedisConfig.java
  src/main/java/org/bob/siungongsi/common/dto/ApiResponseCode.java
  src/main/java/org/bob/siungongsi/common/security/JwtAuthFilter.java
  src/main/java/org/bob/siungongsi/common/security/JwtProvider.java
  src/main/java/org/bob/siungongsi/common/util/RedisUtils.java
  src/main/resources/application-batch.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: 버그-심각

#210 Revert "Revert "feat: 로그아웃 구현 - redis, 블랙리스트 구현""
  build.gradle
  src/main/java/org/bob/siungongsi/api/config/SecurityConfigForApi.java
  src/main/java/org/bob/siungongsi/api/controller/AuthController.java
  src/main/java/org/bob/siungongsi/api/controller/spec/AuthControllerSpec.java
  src/main/java/org/bob/siungongsi/api/service/AuthBlackListService.java
  src/main/java/org/bob/siungongsi/api/service/AuthService.java
  src/main/java/org/bob/siungongsi/common/config/RedisConfig.java
  src/main/java/org/bob/siungongsi/common/dto/ApiResponseCode.java
  src/main/java/org/bob/siungongsi/common/security/JwtAuthFilter.java
  src/main/java/org/bob/siungongsi/common/security/JwtProvider.java
  src/main/java/org/bob/siungongsi/common/util/RedisUtils.java
  src/main/resources/application-batch.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: BE

#211 feat: 레디스 연결 로깅 추가
  src/main/java/org/bob/siungongsi/common/config/RedisConfig.java
Labels: 리팩토링, BE
